const text = [
    "I want you to know I'm a mirrorball I can change everything about me to fit in You are not like the regulars The masquerade revelers Drunk as they watch my shattered edges glisten Hush When no one is around, my dear You'll find me on my tallest tiptoes Spinning in my highest heels, love Shining just for you Hush I know they said the end is near But I'm still on my tallest tiptoes Spinning in my highest heels, love Shining just for you And they called off the circus Burned the disco down When they sent home the horses And the rodeo clowns I'm still on that tightrope I'm still trying everything to get you laughing at me",
    "And you call me up again just to break me like a promise So casually cruel in the name of being honest I'm a crumpled up piece of paper lying here 'Cause I remember it all, all, all Too well Time won't fly, it's like I'm paralyzed by it I'd like to be my old self again But I'm still trying to find it After plaid shirt days and nights when you made me your own Now you mail back my things and I walk home alone But you keep my old scarf from that very first week 'Cause it reminds you of innocence And it smells like me You can't get rid of it 'Cause you remember it all too well",
    "Ladies and gentlemen, will you please stand? With every guitar string scar on my hand I take this magnetic force of a man to be my lover My heart's been borrowed and yours has been blue All's well that ends well to end up with you Swear to be overdramatic and true to my lover And you'll save all your dirtiest jokes for me And at every table, I'll save you a seat, lover Can I go where you go? Can we always be this close forever and ever? And ah, take me out, and take me home (forever and ever) You're my, my, my, my Oh, you're my, my, my, my Darling, you're my, my, my, my Lover",
    "I want auroras and sad prose I want to watch wisteria grow right over my bare feet 'Cause I haven't moved in years And I want you right here A red rose grew up out of ice frozen ground With no one around to tweet it While I bathe in cliffside pools With my calamitous love and insurmountable grief Take me to the lakes where all the poets went to die I don't belong, and my beloved, neither do you Those Windermere peaks look like a perfect place to cry I'm setting off, but not without my muse No, not without you",
    "As if you were a mythical thing Like you were a trophy or a champion ring And there was one prize I'd cheat to win The more that you say The less I know Wherever you stray I follow I'm begging for you to take my hand Wreck my plans That's my man You know that my train could take you home Anywhere else is hollow I'm begging for you to take my hand Wreck my plans That's my man Life was a willow and it bent right to your wind (oh) They count me out time and time again Life was a willow and it bent right to your wind (oh) But I come back stronger than a 90's trend",
    "He said, Let's get out of this town Drive out of the city, away from the crowds I thought heaven can't help me now Nothing lasts forever, but this is gonna take me down He's so tall and handsome as hell He's so bad but he does it so well I can see the end as it begins My one condition is Say you'll remember me standing in a nice dress Staring at the sunset, babe Red lips and rosy cheeks Say you'll see me again Even if it's just in your wildest dreams, ah-ha Wildest dreams",
    "He respects my space and never makes me wait And he calls exactly when he says he will He's close to my mother, talks business with my father He's charming and endearing and I'm comfortable But I miss screaming and fighting and kissing in the rain And it's 2:00 a.m. and I'm cursing your name So in love that you act insane And that's the way I loved you Breakin' down and coming undone It's a roller coaster kinda rush And I never knew I could feel that much And that's the way I loved you He can't see the smile I'm faking And my heart's not breaking",
    "This slope is treacherous This path is reckless This slope is treacherous I, I, I like it Two headlights shine through the sleepless night And I will get you, and get you alone Your name has echoed through my mind And I just think you should, think you should know That nothing safe is worth the drive And I would follow you, follow you home I'll follow you, follow you home This hope is treacherous This daydream is dangerous This hope is treacherous",
    "So we went on our way Too in love to think straight All alone, or so it seemed But there were strangers watching And whispers turned to talking And talking turned to screams, oh Didn't they tell us don't rush into things? Didn't you flash your green eyes at me? Didn't you call my fears with a Cheshire Cat smile? Ooh, didn't it all seem new and exciting? I felt your arms twisting around me It's all fun and games 'til somebody loses their mind Oh, darling, we found Wonderland",
    "The lingering question kept me up Two a.m., who do you love? I wonder till I'm wide awake Now I'm pacing back and forth, wishing you were at my door I'd open up and you would say, hey It was enchanting to meet you All I know is I was, enchanted to meet you This night is sparkling, don't you let it go I'm wonder struck, blushing all the way home I'll spend forever wondering if you knew This night is flawless, don't you let it go I'm wonder struck, dancing around all alone I'll spend forever wondering if you knew I was enchanted to meet you",
    "Is it cool that I said all that? Is it too soon to do this yet? 'Cause I know that it's delicate Isn't it, isn't it, isn't it? Isn't it? Isn't it, isn't it, isn't it? Isn't it delicate? Third floor on the West Side, me and you Handsome, you're a mansion with a view Do the girls back home touch you like I do? Long night with your hands up in my hair Echoes of your footsteps on the stairsStay here, honey, I don't want to share 'Cause I like you",
    "Back when we were still changin' for the better Wanting was enough For me, it was enough To live for the hope of it all Cancel plans just in case you'd call And say, Meet me behind the mall So much for summer love and saying us 'Cause you weren't mine to lose You weren't mine to lose, no But I can see us lost in the memory August slipped away into a moment in time 'Cause it was never mine And I can see us twisted in bedsheets August sipped away like a bottle of wine 'Cause you were never mine",
    "'Cause when you're fifteen, Somebody tells you they love you You're gonna believe them And when you're fifteen Feeling like there's nothing to figure out Count to ten Take it in This is life before you know who you're gonna be At fifteen You sit in class next to a red-head named Abigail And soon enough you're best friends Laughing at the other girls",
    "I think I've seen this film before And I didn't like the ending I'm not your problem anymore So who am I offending now? You were my crown Now I'm in exile, seein' you out I think I've seen this film before So I'm leavin' out the side door So step right out, there is no amount Of crying I can do for you All this time We always walked a very thin line You didn't even hear me out (You didn't even hear me out) You never gave a warning sign",
    "But she wears short skirts I wear T-shirts She's Cheer Captain, and I'm on the bleachers Dreaming about the day when you wake up and find That what you're looking for has been here the whole time If you could see that I'm the one Who understands you Been here all along So, why can't you see? You belong with me You belong with me Walk in the streets with you in your worn-out jeans",
    "It keeps me awake The look on your face The moment you heard the news You're screaming inside And frozen in time You did all that you could do The game was rigged, the ref got tricked The wrong ones think they're right You were outnumbered, this time But only the young Only the young Only the young Only the young can run",
    "And I ain't trying mess with your self-expression But I've learned the lesson that stressin' And obsessin' 'bout somebody else is no fun And snakes and stones never broke my bones so So, oh-oh, oh-oh, oh-oh, oh-oh, oh-oh You need to calm down You're being too loud And I'm just like oh-oh, oh-oh, oh-oh, oh-oh, oh-oh",
    "I'm so sick of running as fast as I can Wondering if I'd get there quicker If I was a man And I'm so sick of them coming at me again 'Cause if I was a man Then I'd be the man I'd be the man I'd be the man They'd say I hustled Put in the work They wouldn't shake their heads and question how much of this I deserve What I was wearing If I was rude Could all be separated from my good ideas and power moves?"
];

export default text;